---
- include_vars: var_debian.yml

- name: Check if my_env path exist
  stat: path={{v_env}}
  register: virt_env

- name: Update Cache
  apt:
    upgrade=yes
    update_cache=yes    cache_valid_time=360000

- name: Install Python
  apt:
    name={{item}}
    state=present
  with_items: "{{tools}}"

- name: Install pytools using pip 
  pip:
    name={{item}}
    executable=pip3
  with_items: "{{pip_tools}}"

- name: Create virtual environment path
  file:
    path="{{env_dir}}"
    state=directory
    owner=root 
    group=root 
    mode=0755
  when: env_dir is defined and virt_env.stat.exists == false

- name: Check python version and create virtual environment 
  command: "{{item}} chdir=~/environments"
  with_items:
    - "{{cmd}}"
  when: virt_env.stat.exists == false