---
- name: Ensure MySQL packages are installed
  yum: name={{item}} state=present enablerepo={{mysql_repo}}
  with_items: "{{rh_mysql_packages}}"
  register: rh_mysql_installed
- debug: var=rh_mysql_installed
